//yeni
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-2bYx5f9smmJwmZSFLL1hnxDauEgnso4',
    appId: '1:221332128964:web:e165b8d3f721d8d35a7591',
    messagingSenderId: '221332128964',
    projectId: 'fire-setup-4d3c8',
    authDomain: 'fire-setup-4d3c8.firebaseapp.com',
    storageBucket: 'fire-setup-4d3c8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkyGKDRtEMwYdOtmoMUNeqody8ymzshIQ',
    appId: '1:221332128964:android:20cf749e10a4e9ae5a7591',
    messagingSenderId: '221332128964',
    projectId: 'fire-setup-4d3c8',
    storageBucket: 'fire-setup-4d3c8.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-2bYx5f9smmJwmZSFLL1hnxDauEgnso4',
    appId: '1:221332128964:web:831fd35a8b84fcce5a7591',
    messagingSenderId: '221332128964',
    projectId: 'fire-setup-4d3c8',
    authDomain: 'fire-setup-4d3c8.firebaseapp.com',
    storageBucket: 'fire-setup-4d3c8.firebasestorage.app',
  );
}
